# Generated by Django 6.0.3 on 2026-05-10 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_app_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(choices=[('auto', 'Auto-matched')], default='auto', max_length=10)),
                ('status', models.CharField(choices=[('paired', 'Paired'), ('unmatched', 'Unmatched')], default='paired', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming', models.OneToOneField(blank=True, help_text='The incoming (credit/deposit) side of the transfer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_incoming', to='core.rawtransaction')),
                ('outgoing', models.OneToOneField(blank=True, help_text='The outgoing (debit) side of the transfer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_outgoing', to='core.rawtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
