# Generated by Django 6.0.3 on 2026-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transactionpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sign_factor',
            field=models.SmallIntegerField(default=1, help_text='1 for debit (standard signs), -1 for credit (flip signs on LogicalTransaction)'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='normalized_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standardized amount: negative=out, positive=in (amount × account.sign_factor)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original amount from bank statement', max_digits=14),
        ),
    ]
