# Generated by Django 6.0.3 on 2026-05-11 04:06

from django.db import migrations


def backfill_sign_factor_and_normalized_amount(apps, schema_editor):
    """
    1. Set sign_factor = -1 on all CreditAccount records
    2. Compute normalized_amount = amount × sign_factor for all RawTransactions
    3. Flip LogicalTransaction amount/amount_crc/amount_usd for credit card transactions
    """
    Account = apps.get_model('core', 'Account')
    CreditAccount = apps.get_model('core', 'CreditAccount')
    RawTransaction = apps.get_model('core', 'RawTransaction')
    LogicalTransaction = apps.get_model('core', 'LogicalTransaction')

    # Step 1: Set sign_factor on credit accounts
    credit_account_ids = set(
        CreditAccount.objects.values_list('account_ptr_id', flat=True)
    )
    Account.objects.filter(pk__in=credit_account_ids).update(sign_factor=-1)

    # Step 2: Backfill normalized_amount on all RawTransactions
    # Debit accounts: normalized_amount = amount (sign_factor = 1)
    # Credit accounts: normalized_amount = -amount (sign_factor = -1)
    # We need to go through ledger → statement_import → account to find the sign_factor
    from django.db.models import F
    StatementImport = apps.get_model('core', 'StatementImport')
    CurrencyLedger = apps.get_model('core', 'CurrencyLedger')

    # Get all ledger IDs belonging to credit accounts
    credit_statement_ids = set(
        StatementImport.objects.filter(account_id__in=credit_account_ids)
        .values_list('id', flat=True)
    )
    credit_ledger_ids = set(
        CurrencyLedger.objects.filter(statement_import_id__in=credit_statement_ids)
        .values_list('id', flat=True)
    )

    # Debit raw transactions: normalized = amount
    RawTransaction.objects.exclude(ledger_id__in=credit_ledger_ids).update(
        normalized_amount=F('amount')
    )
    # Credit raw transactions: normalized = -amount
    RawTransaction.objects.filter(ledger_id__in=credit_ledger_ids).update(
        normalized_amount=-F('amount')
    )

    # Step 3: Flip LogicalTransaction amounts for credit card transactions
    credit_raw_ids = set(
        RawTransaction.objects.filter(ledger_id__in=credit_ledger_ids)
        .values_list('id', flat=True)
    )
    LogicalTransaction.objects.filter(raw_transaction_id__in=credit_raw_ids).update(
        amount=-F('amount'),
        amount_crc=-F('amount_crc'),
        amount_usd=-F('amount_usd'),
    )


def reverse_backfill(apps, schema_editor):
    """Reverse: flip credit card signs back and reset normalized_amount."""
    Account = apps.get_model('core', 'Account')
    CreditAccount = apps.get_model('core', 'CreditAccount')
    RawTransaction = apps.get_model('core', 'RawTransaction')
    LogicalTransaction = apps.get_model('core', 'LogicalTransaction')
    StatementImport = apps.get_model('core', 'StatementImport')
    CurrencyLedger = apps.get_model('core', 'CurrencyLedger')
    from django.db.models import F

    credit_account_ids = set(
        CreditAccount.objects.values_list('account_ptr_id', flat=True)
    )
    credit_statement_ids = set(
        StatementImport.objects.filter(account_id__in=credit_account_ids)
        .values_list('id', flat=True)
    )
    credit_ledger_ids = set(
        CurrencyLedger.objects.filter(statement_import_id__in=credit_statement_ids)
        .values_list('id', flat=True)
    )
    credit_raw_ids = set(
        RawTransaction.objects.filter(ledger_id__in=credit_ledger_ids)
        .values_list('id', flat=True)
    )

    # Flip LogicalTransaction signs back
    LogicalTransaction.objects.filter(raw_transaction_id__in=credit_raw_ids).update(
        amount=-F('amount'),
        amount_crc=-F('amount_crc'),
        amount_usd=-F('amount_usd'),
    )

    # Reset normalized_amount
    RawTransaction.objects.all().update(normalized_amount=None)

    # Reset sign_factor
    Account.objects.filter(pk__in=credit_account_ids).update(sign_factor=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_sign_factor_and_normalized_amount'),
    ]

    operations = [
        migrations.RunPython(
            backfill_sign_factor_and_normalized_amount,
            reverse_backfill,
        ),
    ]
