# Generated by Django 6.0.3 on 2026-05-14 02:55

from django.db import migrations


def rename_forward(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(name='Unclassified Unclassified').update(name='Unclassified')


def rename_reverse(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(name='Unclassified').update(name='Unclassified Unclassified')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_transaction_slug_to_transfer'),
    ]

    operations = [
        migrations.RunPython(rename_forward, rename_reverse),
    ]
