# Generated by Django 6.0.3 on 2026-10-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_unclassified_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for charts', max_length=7)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='category_nodes',
                    to='core.categorygroup',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='category_nodes',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('parent', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='children',
                    to='core.categorynode',
                )),
            ],
            options={
                'ordering': ['group', 'name'],
                'unique_together': {('name', 'group', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='categorynode',
            constraint=models.CheckConstraint(
                condition=~models.Q(('id', models.F('parent_id'))),
                name='category_node_not_own_parent',
            ),
        ),
    ]
