# Generated by Django 6.1.1 on 2026-10-03 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categorynode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRuleV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Case-insensitive substring match', max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('credit_account', 'Credit Account'), ('debit_account', 'Debit Account')], max_length=20)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Key-value conditions, e.g. {"transaction_code": "PT"}')),
                ('detail', models.CharField(blank=True, help_text='Documentation note', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='core.categorynode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'classification rule (v2)',
                'verbose_name_plural': 'classification rules (v2)',
                'ordering': ['category__group__slug', 'category__name', 'description'],
            },
        ),
    ]
