# Generated by Django 6.1.1 on 2026-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_classificationrulev2'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicaltransaction',
            name='category_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logical_transactions', to='core.categorynode'),
        ),
        migrations.AddField(
            model_name='logicaltransaction',
            name='classification_method_v2',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('rule', 'Rule'), ('manual', 'Manual')], default='unclassified', max_length=15),
        ),
        migrations.AddField(
            model_name='logicaltransaction',
            name='matched_rule_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='core.classificationrulev2'),
        ),
    ]
