# Generated by Django 6.1.1 on 2026-10-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_logicaltransaction_v2_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicaltransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='classificationrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='classificationrule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logicaltransaction',
            name='matched_rule',
        ),
        migrations.RemoveField(
            model_name='logicaltransaction',
            name='classification_method',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ClassificationRule',
        ),
    ]
