# Generated by Django 6.1.1 on 2026-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_v1_categories_and_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicaltransaction',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
