# Generated by Django 6.1.1 on 2026-10-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrulev2',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rules', to='core.tag'),
        ),
    ]
