# Generated by Django 6.0.3 on 2026-04-07 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Optional friendly name', max_length=100)),
                ('account_type', models.CharField(choices=[('credit_account', 'Credit Account'), ('debit_account', 'Debit Account')], max_length=20)),
            ],
            options={
                'ordering': ['-account_type'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transaction', 'Transfer'), ('unclassified', 'Unclassified')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usd_to_crc', models.DecimalField(decimal_places=4, help_text='1 USD = X CRC', max_digits=10)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.account')),
                ('card_number', models.CharField(max_length=30, unique=True)),
            ],
            bases=('transactions.account',),
        ),
        migrations.CreateModel(
            name='DebitAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.account')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('client_number', models.CharField(blank=True, max_length=20)),
            ],
            bases=('transactions.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for charts', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='transactions.categorygroup')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['group', 'name'],
                'unique_together': {('name', 'group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Case-insensitive substring match', max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('credit_account', 'Credit Account'), ('debit_account', 'Debit Account')], max_length=20)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Key-value conditions, e.g. {"transaction_code": "PT"}')),
                ('detail', models.CharField(blank=True, help_text='Documentation note', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__group__slug', 'category__name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('CRC', 'Costa Rican Colón'), ('USD', 'US Dollar')], max_length=3)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_at_cutoff', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account_metadata', models.JSONField(blank=True, default=dict, help_text='Account-type-specific data (e.g. transaction_code, reference_number for debit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_transactions', to='transactions.currencyledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogicalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_crc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('classification_method', models.CharField(choices=[('unclassified', 'Unclassified'), ('rule', 'Rule'), ('manual', 'Manual')], default='unclassified', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logical_transactions', to='transactions.category')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='transactions.classificationrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_transactions', to=settings.AUTH_USER_MODEL)),
                ('raw_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_transactions', to='transactions.rawtransaction')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the file content', max_length=64)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('points_assigned', models.PositiveIntegerField(default=0)),
                ('points_redeemable', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='transactions.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.AddField(
            model_name='currencyledger',
            name='statement_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='transactions.statementimport'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyledger',
            unique_together={('statement_import', 'currency')},
        ),
    ]
