# Generated by Django 6.0.3 on 2026-04-12 02:26

import hashlib
from django.db import migrations, models


def convert_card_numbers(apps, schema_editor):
    """Hash existing card numbers and extract last 4 digits."""
    CreditAccount = apps.get_model('transactions', 'CreditAccount')
    for account in CreditAccount.objects.all():
        account.card_number_hash = hashlib.sha256(account.card_number.encode()).hexdigest()
        account.card_number_last4 = account.card_number[-4:]
        account.save(update_fields=['card_number_hash', 'card_number_last4'])


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_userpreference'),
    ]

    operations = [
        # Step 1: Add new fields (nullable/with defaults so existing rows are fine)
        migrations.AddField(
            model_name='creditaccount',
            name='card_number_hash',
            field=models.CharField(default='', help_text='SHA-256 hash of full card number', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='card_number_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits for display', max_length=4),
        ),
        # Step 2: Populate new fields from old card_number
        migrations.RunPython(convert_card_numbers, migrations.RunPython.noop),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='creditaccount',
            name='card_number',
        ),
        # Step 4: Add unique constraint on hash
        migrations.AlterField(
            model_name='creditaccount',
            name='card_number_hash',
            field=models.CharField(help_text='SHA-256 hash of full card number', max_length=64, unique=True),
        ),
    ]
